version: "3.7"

services:

  jupyter:

    build: ./jupyter

    command: "jupyter notebook -p 8888:8888 --ip 0.0.0.0 --no-browser --allow-root"    # argument for entrypoint script
    volumes:
      - ./:/jupyter
    ports:
      - "8888:8888"
      - "22:22"
    restart: unless-stopped